version: '2'

services:

  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=order_db
      - MYSQL_USER=order_user
      - MYSQL_PASSWORD=order_password
    ports:
      - 3306:3306
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    container_name: qiangyt-monothilic-springboot-example.mysql

  rabbitmq:
    image: rabbitmq:3.8.0-management
    container_name: qiangyt-monothilic-springboot-example.rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./tmp/rabbitmq:/var/lib/rabbitmq
    networks:
      default:

  server:
    build:
      context: ./
    container_name: qiangyt-monothilic-springboot-example.server
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - WAIT_LIST=mysql:3306
      - WAIT_TIMEOUT=60
      - SPRING_PROFILES_ACTIVE=test
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./server/config:/opt/app/config:ro
