###
GET http://localhost:8180/api/accounts/all

###
OPTIONS http://localhost:8180/api/auth/signin/byName/admin

pwd

###
POST http://localhost:8180/api/auth/signin/byName/admin
Content-Type: application/json; charset=utf-8

pwd


###
GET http://localhost:8180/api/products/all

###
POST http://localhost:8180/api/orders
Content-Type: application/json; charset=utf-8

{
    "customerAccountId": "a507f8c5-2974-4a46-b7f5-82040a8eab9f",
    "productId": "04a84023-7f42-4825-90f4-77408d5d0fdd",
    "amount": 88
}

